version: '3'

services:
  frontend:
    image: node:alpine
    working_dir: /usr/src/app
    # build:
    #   context: .
    #   dockerfile: services/frontend
    command: > 
      bash -c "npm install && npm start"
    env_file:
      - ./config/config.env
    volumes:
      - ./services/frontend:/usr/src/app
      - node_modules-frontend-volume:/usr/src/app/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules-frontend-volume:

  